package generator.website;

import org.eclipse.emf.common.util.EList;
import java.lang.String;
import robot.*;;

public class SimpleToURBI
{
  protected static String nl;
  public static synchronized SimpleToURBI create(String lineSeparator)
  {
    nl = lineSeparator;
    SimpleToURBI result = new SimpleToURBI();
    nl = null;
    return result;
  }

  public final String NL = nl == null ? (System.getProperties().getProperty("line.separator")) : nl;
  protected final String TEXT_1 = "/*" + NL + " * Urbi code generated by Model" + NL + " * Code generation made by Thibault Duperron and Nicolas Rignault" + NL + " * CAR Project 2010" + NL + " */" + NL + "" + NL + "// Add e-puck basic functions" + NL + "load(\"e-puck/e-puck.u\");" + NL + "" + NL + "// Program" + NL + "{";
  protected final String TEXT_2 = NL;
  protected final String TEXT_3 = NL + "}";
  protected final String TEXT_4 = NL;

  public String generate(Object argument)
  {
    final StringBuffer stringBuffer = new StringBuffer();
    Mission mission = (Mission) argument; 
    stringBuffer.append(TEXT_1);
    Sequence programme = mission.getSequence();
    EList<Operation> listOperation = programme.getOperations();
    for (Operation operation : listOperation) {
    stringBuffer.append(TEXT_2);
    stringBuffer.append(operation.toUrbiString("\t"));
    } 
    stringBuffer.append(TEXT_3);
    stringBuffer.append(TEXT_4);
    return stringBuffer.toString();
  }
}
